abstract class ApiKeys{
  static const String publishableKey='pk_test_51O0MSSDuDIqSHhLntVmR5ZSuNwyDvhStOCNEDXPJ9ZYNW1WeEhP15eYatywLchq9TTtfSCTnOO70aBNY6WcKnqtW000NJnVSXK';
  static const String secretKey='sk_test_51O0MSSDuDIqSHhLnARRqrdnkMjncXwIivkNRYK8YeeNnOs1b2ZPrmtwLCUzyEUoXRjDvTn6vhX3vYnKjCP0brj8A00lRCvEvbR';

}